### ISSUE TITLE
(node:2982) UnhandledPromiseRejectionWarning: Error: spawnSync npm ENOBUFS

### ISSUE THREAD

**Issue by ssmall** [oke-py/npm-audit-action#66]
**What happened**:
We see this error when time npm-audit-action runs:
```
(node:2982) UnhandledPromiseRejectionWarning: Error: spawnSync npm ENOBUFS
    at Object.spawnSync (internal/child_process.js:1041:20)
    at Object.spawnSync (child_process.js:607:24)
    at Audit.<anonymous> (/home/runner/work/_actions/oke-py/npm-audit-action/v1.5.0/dist/index.js:1134:48)
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/oke-py/npm-audit-action/v1.5.0/dist/index.js:1116:71
    at new Promise (<anonymous>)
    at module.exports.50.__awaiter (/home/runner/work/_actions/oke-py/npm-audit-action/v1.5.0/dist/index.js:1112:12)
    at Audit.run (/home/runner/work/_actions/oke-py/npm-audit-action/v1.5.0/dist/index.js:1132:16)
    at /home/runner/work/_actions/oke-py/npm-audit-action/v1.5.0/dist/index.js:3321:19
    at Generator.next (<anonymous>)
(node:2982) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2982) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

[example failure](https://github.com/GoogleCloudPlatform/cloud-run-anthos-reference-web-app/runs/834993495?check_suite_focus=true)

**What you expected to happen**: Action should succeed without error

**How you configured .github/workflows/**:

See https://github.com/GoogleCloudPlatform/cloud-run-anthos-reference-web-app/blob/master/.github/workflows/npm-audit-periodic.yaml

**Anything else we need to know?**: This appears to be a similar issue to what is described in https://github.com/jfrog/jfrog-vscode-extension/issues/20

**Comment by ssmall** [comment]
I am working on a fix for this in my fork (https://github.com/ssmall/npm-audit-action) and will submit a pull request once I have had a chance to test it

**Comment by oke-py** [comment]
@ssmall v1.5.1 was released. Thanks!
